CREATE DATABASE Barcodes
GO

USE Barcodes
GO

CREATE TABLE Profiles
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Surname VARCHAR(50) NOT NULL,
	Name VARCHAR(35) NOT NULL,
	System_role VARCHAR(30) NOT NULL,
	Profile_login VARCHAR(30) UNIQUE NOT NULL,
	Profile_password VARCHAR(16) NOT NULL
)
GO

CREATE TABLE Countries
(
	Country VARCHAR(50) PRIMARY KEY NOT NULL
)
GO

CREATE TABLE Barcodes
(
	Barcode VARCHAR(15) PRIMARY KEY NOT NULL
)
GO

CREATE TABLE Country_barcodes
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Country VARCHAR(50) FOREIGN KEY REFERENCES Countries(Country) NOT NULL,
	Barcode VARCHAR(15) FOREIGN KEY REFERENCES Barcodes(Barcode) NOT NULL
)
GO