//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SystemRole { get; set; }
        public string ProfileLogin { get; set; }
        public string ProfilePassword { get; set; }
    }
}
